#!/bin/sh
#PMD_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#if [ "$#" -eq 1 ]
#then
	#if [ "$1" == "break" ]
	#then
		#($PMD_DIR/pmd-counter 5)&
	#else 
		#($PMD_DIR/pmd-counter $1)&
	#fi
#else
	#($PMD_DIR/pmd-counter 25)&
#fi


